### ISSUE TITLE
It doesn't process the clip at all

### ISSUE THREAD

**Issue by CamiloMM** [Asd-g/AviSynthPlus-BlockDetect#1]
As in, the output is the same as the input. Maybe I'm mistaken in how a filter like this would operate? I assumed it'd create a mask of blockiness detection or something like that.
<img width="669" alt="image" src="https://user-images.githubusercontent.com/2404138/229882884-f7760228-686c-45f2-b8f7-c32b59cbce90.png">

**Comment by Asd-g** [comment]
It determines blockiness of frames by adding the relevant frame property. Put `propShow()` at the end of the script.

**Comment by CamiloMM** [comment]
> propShow()

Learned something new today.
Thanks!
